server:
  port: 8765
  
spring:
  application:
    name: cloudgateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

  security:
    user:
      name: sid
      password: 15